dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'
install: pip install pytest
script: py.test --doctest-modules --doctest-glob=*.test --doctest-glob=*.tests
notifications:
  email: false
  slack: jalanb:wqEssxDWp8j7FAaeNoOxz0z6#travis
deploy:
  provider: pypi
  user: jalanb
  on:
    tags: true
  password:
    secure: g/XxaPnc2BgNWDy66OLyJ4lavMNUqmy8uwJzqBy52LZQ8+tRk+GMUo5fncIBju/Gr1vNechrx1dfEyAEFQo80dlFhSIVm2UHn/2bV2j7iMH/y3timoNnFbIW9S3M54vHRhwg2G3JgU3Stzy5B/Rbxk8sruFb6juf08T5xXTfH3A=
